#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    NoRootAuthority(Option<NoRootAuthority_Args>),
    ParseFailed(Option<ParseFailed_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::NoRootAuthority(v) => {
                write!(f, "org.avocado.RootAuthority.NoRootAuthority: {:#?}", v)
            }
            ErrorKind::ParseFailed(v) => {
                write!(f, "org.avocado.RootAuthority.ParseFailed: {:#?}", v)
            }
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. }
                if t == "org.avocado.RootAuthority.NoRootAuthority" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::NoRootAuthority(v),
                        Err(_) => ErrorKind::NoRootAuthority(None),
                    },
                    _ => ErrorKind::NoRootAuthority(None),
                }
            }
            varlink::Reply { error: Some(t), .. }
                if t == "org.avocado.RootAuthority.ParseFailed" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::ParseFailed(v),
                        Err(_) => ErrorKind::ParseFailed(None),
                    },
                    _ => ErrorKind::ParseFailed(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_no_root_authority(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.RootAuthority.NoRootAuthority",
            None,
        ))
    }
    fn reply_parse_failed(&mut self, r#reason: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.RootAuthority.ParseFailed",
            Some(
                serde_json::to_value(ParseFailed_Args { r#reason })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#RootAuthorityInfo {
    pub r#version: i64,
    pub r#expires: String,
    pub r#keys: Vec<TrustedKey>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#TrustedKey {
    pub r#keyId: String,
    pub r#keyType: String,
    pub r#roles: Vec<String>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct NoRootAuthority_Args {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct ParseFailed_Args {
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Show_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#authority: Option<RootAuthorityInfo>,
}
impl varlink::VarlinkReply for Show_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Show_Args {}
#[allow(dead_code)]
pub trait Call_Show: VarlinkCallError {
    fn reply(&mut self, r#authority: Option<RootAuthorityInfo>) -> varlink::Result<()> {
        self.reply_struct(Show_Reply { r#authority }.into())
    }
}
impl Call_Show for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn show(&self, call: &mut dyn Call_Show) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn show(&mut self) -> varlink::MethodCall<Show_Args, Show_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn show(&mut self) -> varlink::MethodCall<Show_Args, Show_Reply, Error> {
        varlink::MethodCall::<Show_Args, Show_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.RootAuthority.Show",
            Show_Args {},
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "# Trust anchor / root authority information\ninterface org.avocado.RootAuthority\n\ntype TrustedKey (\n    keyId: string,\n    keyType: string,\n    roles: []string\n)\n\ntype RootAuthorityInfo (\n    version: int,\n    expires: string,\n    keys: []TrustedKey\n)\n\n# Show the trusted signing keys for this device\nmethod Show() -> (authority: ?RootAuthorityInfo)\n\nerror NoRootAuthority ()\nerror ParseFailed (reason: string)\n"
    }
    fn get_name(&self) -> &'static str {
        "org.avocado.RootAuthority"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "org.avocado.RootAuthority.Show" => self.inner.show(call as &mut dyn Call_Show),
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
