#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::{Arc, RwLock};
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    MountFailed(Option<MountFailed_Args>),
    UnmountFailed(Option<UnmountFailed_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::MountFailed(v) => write!(f, "org.avocado.Hitl.MountFailed: {:#?}", v),
            ErrorKind::UnmountFailed(v) => write!(f, "org.avocado.Hitl.UnmountFailed: {:#?}", v),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. } if t == "org.avocado.Hitl.MountFailed" => match e
            {
                varlink::Reply {
                    parameters: Some(p),
                    ..
                } => match serde_json::from_value(p.clone()) {
                    Ok(v) => ErrorKind::MountFailed(v),
                    Err(_) => ErrorKind::MountFailed(None),
                },
                _ => ErrorKind::MountFailed(None),
            },
            varlink::Reply { error: Some(t), .. } if t == "org.avocado.Hitl.UnmountFailed" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::UnmountFailed(v),
                        Err(_) => ErrorKind::UnmountFailed(None),
                    },
                    _ => ErrorKind::UnmountFailed(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_mount_failed(&mut self, r#extension: String, r#reason: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Hitl.MountFailed",
            Some(
                serde_json::to_value(MountFailed_Args {
                    r#extension,
                    r#reason,
                })
                .map_err(varlink::map_context!())?,
            ),
        ))
    }
    fn reply_unmount_failed(
        &mut self,
        r#extension: String,
        r#reason: String,
    ) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.avocado.Hitl.UnmountFailed",
            Some(
                serde_json::to_value(UnmountFailed_Args {
                    r#extension,
                    r#reason,
                })
                .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct MountFailed_Args {
    pub r#extension: String,
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct UnmountFailed_Args {
    pub r#extension: String,
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Mount_Reply {}
impl varlink::VarlinkReply for Mount_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Mount_Args {
    pub r#serverIp: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#serverPort: Option<String>,
    pub r#extensions: Vec<String>,
}
#[allow(dead_code)]
pub trait Call_Mount: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_Mount for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Unmount_Reply {}
impl varlink::VarlinkReply for Unmount_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Unmount_Args {
    pub r#extensions: Vec<String>,
}
#[allow(dead_code)]
pub trait Call_Unmount: VarlinkCallError {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
impl Call_Unmount for varlink::Call<'_> {}
#[allow(dead_code)]
pub trait VarlinkInterface {
    fn mount(
        &self,
        call: &mut dyn Call_Mount,
        r#serverIp: String,
        r#serverPort: Option<String>,
        r#extensions: Vec<String>,
    ) -> varlink::Result<()>;
    fn unmount(
        &self,
        call: &mut dyn Call_Unmount,
        r#extensions: Vec<String>,
    ) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn mount(
        &mut self,
        r#serverIp: String,
        r#serverPort: Option<String>,
        r#extensions: Vec<String>,
    ) -> varlink::MethodCall<Mount_Args, Mount_Reply, Error>;
    fn unmount(
        &mut self,
        r#extensions: Vec<String>,
    ) -> varlink::MethodCall<Unmount_Args, Unmount_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn mount(
        &mut self,
        r#serverIp: String,
        r#serverPort: Option<String>,
        r#extensions: Vec<String>,
    ) -> varlink::MethodCall<Mount_Args, Mount_Reply, Error> {
        varlink::MethodCall::<Mount_Args, Mount_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Hitl.Mount",
            Mount_Args {
                r#serverIp,
                r#serverPort,
                r#extensions,
            },
        )
    }
    fn unmount(
        &mut self,
        r#extensions: Vec<String>,
    ) -> varlink::MethodCall<Unmount_Args, Unmount_Reply, Error> {
        varlink::MethodCall::<Unmount_Args, Unmount_Reply, Error>::new(
            self.connection.clone(),
            "org.avocado.Hitl.Unmount",
            Unmount_Args { r#extensions },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}
impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "# Hardware-in-the-loop testing support\ninterface org.avocado.Hitl\n\n# Mount NFS extensions from a remote server\nmethod Mount(serverIp: string, serverPort: ?string, extensions: []string) -> ()\n\n# Unmount NFS extensions\nmethod Unmount(extensions: []string) -> ()\n\nerror MountFailed (extension: string, reason: string)\nerror UnmountFailed (extension: string, reason: string)\n"
    }
    fn get_name(&self) -> &'static str {
        "org.avocado.Hitl"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "org.avocado.Hitl.Mount" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Mount_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.mount(
                        call as &mut dyn Call_Mount,
                        args.r#serverIp,
                        args.r#serverPort,
                        args.r#extensions,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "org.avocado.Hitl.Unmount" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Unmount_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner
                        .unmount(call as &mut dyn Call_Unmount, args.r#extensions)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
